### ISSUE TITLE
Allow login with Google accounts

### ISSUE THREAD

**Issue by kraglalbert** [hack4impact-mcgill/move-up-crm-tool#37]
Move Up requested that they be able to log in to the application using their Google accounts, so we should integrate Google OAuth into our app.

Only email accounts that end with `@moveuptoday.org` should be allowed to log in.

Potentially useful links:

* https://developers.google.com/identity/sign-in/web/sign-in
* https://developers.google.com/identity/sign-in/web
* https://auth0.com/docs/connections/social/google

**Comment by eidil** [comment]
Do we just need google accounts or others too? @kraglalbert

**Comment by eidil** [comment]
Closing this since we have another one
