### ISSUE TITLE
Sign out button

### ISSUE THREAD

**Issue by eidil** [hack4impact-mcgill/move-up-crm-tool#54]

**Comment by eidil** [comment]
Mentors can be able to sign out from any page

**Comment by eidil** [comment]
@CurtisMIT maybe you should take on this since you're working on the sign in sign out page too

**Comment by celinehuang** [comment]
@tedspare I added the frontend button (top right on the image) but the backend function is not implemented with the button. Feel free to move it elsewhere when you get around to it!
![image](https://user-images.githubusercontent.com/33935299/76687481-ab656600-65fa-11ea-84d4-5f12f41a9b3c.png)
